sudo: required
language: java
jdk: openjdk11

services:
  - docker
  - postgresql

before_script:
  - bash ./.travis/install-postgres-11.sh
  - psql -c 'create database travis_ci_test;' -U postgres

git:
  depth: 9999999

script:
  - ./gradlew test -i

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'
