sudo: required
language: java
jdk: openjdk11

services:
  - docker

before_script:
  - bash ./.travis/install-postgres-11.sh

git:
  depth: 9999999

script:
  - ./gradlew test -i

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'
